### 컬럼 추가

DataFrame 생성

In [18]:
import pandas as pd

dataframe = pd.DataFrame({
    "eno": [1, 2, 3, 4, 5],
    "name": ["춘봄이", "하여름", "추가을", "동겨울", "춘순이"],
    "dept": ["개발팀", "분석팀", "홍보팀", "인사팀", "설계팀"],
    "date": [
        pd.to_datetime("2015-09-22"),
        pd.to_datetime("2016-09-22"),
        pd.to_datetime("2017-09-22"),
        pd.to_datetime("2018-09-22"),
        pd.to_datetime("2019-09-22")
    ],
    "salary": [8000, 7500, 7300, 7200, 7700]
})

dataframe

   eno name dept       date  salary
0    1  춘봄이  개발팀 2015-09-22    8000
1    2  하여름  분석팀 2016-09-22    7500
2    3  추가을  홍보팀 2017-09-22    7300
3    4  동겨울  인사팀 2018-09-22    7200
4    5  춘순이  설계팀 2019-09-22    7700

맨 끝에 새로운 컬럼 추가

In [19]:
dataframe["city"] = "서울"
dataframe

   eno name dept       date  salary city
0    1  춘봄이  개발팀 2015-09-22    8000   서울
1    2  하여름  분석팀 2016-09-22    7500   서울
2    3  추가을  홍보팀 2017-09-22    7300   서울
3    4  동겨울  인사팀 2018-09-22    7200   서울
4    5  춘순이  설계팀 2019-09-22    7700   서울

In [20]:
dataframe["position"] = ["사원", "대리", "과장", "차장", "부장"]
dataframe

   eno name dept       date  salary city position
0    1  춘봄이  개발팀 2015-09-22    8000   서울       사원
1    2  하여름  분석팀 2016-09-22    7500   서울       대리
2    3  추가을  홍보팀 2017-09-22    7300   서울       과장
3    4  동겨울  인사팀 2018-09-22    7200   서울       차장
4    5  춘순이  설계팀 2019-09-22    7700   서울       부장

주어진 위치에 컬럼 삽입

In [21]:
dataframe.insert(3, "sex", ["남","여","여","남","남"])
dataframe

   eno name dept sex       date  salary city position
0    1  춘봄이  개발팀   남 2015-09-22    8000   서울       사원
1    2  하여름  분석팀   여 2016-09-22    7500   서울       대리
2    3  추가을  홍보팀   여 2017-09-22    7300   서울       과장
3    4  동겨울  인사팀   남 2018-09-22    7200   서울       차장
4    5  춘순이  설계팀   남 2019-09-22    7700   서울       부장

In [22]:
dataframe.insert(7, "work", 1)
dataframe

   eno name dept sex       date  salary city  work position
0    1  춘봄이  개발팀   남 2015-09-22    8000   서울     1       사원
1    2  하여름  분석팀   여 2016-09-22    7500   서울     1       대리
2    3  추가을  홍보팀   여 2017-09-22    7300   서울     1       과장
3    4  동겨울  인사팀   남 2018-09-22    7200   서울     1       차장
4    5  춘순이  설계팀   남 2019-09-22    7700   서울     1       부장

### 컬럼 삭제

In [296]:
dataframe.drop(
    columns=["sex", "city", "work", "position"], 
    inplace=True
)
print(dataframe)

   eno name dept       date  salary
0    1  춘봄이  개발팀 2015-09-22    8000
1    2  하여름  분석팀 2016-09-22    7500
2    3  추가을  홍보팀 2017-09-22    7300
3    4  동겨울  인사팀 2018-09-22    7200
4    5  춘순이  설계팀 2019-09-22    7700