### DataFrame 속성

In [9]:
import pandas as pd
import numpy as np

DataFrame 생성

In [20]:
pname = ["오렌지", "바나나", "딸기", "사과"]
pprice = [3000, 2000, 6000, 4500]
pstock = [50, 30, 10, 100]
porigin = ["미국", "필리핀", "한국", "한국"]
pdate = ["2019-01-01", "2019-02-01", "2019-03-01", "2019-04-01"]

dataframe = pd.DataFrame({
    "PNAME":pname,
    "PPRICE":pprice,
    "PSTOCK":pstock,
    "PORIGIN":porigin,
    "PDATE": pdate
})

dataframe

  PNAME  PPRICE  PSTOCK PORIGIN       PDATE
0   오렌지    3000      50      미국  2019-01-01
1   바나나    2000      30     필리핀  2019-02-01
2    딸기    6000      10      한국  2019-03-01
3    사과    4500     100      한국  2019-04-01

index 속성과 columns 속성

In [22]:
print(dataframe.index)
print(dataframe.columns)

RangeIndex(start=0, stop=4, step=1)
Index(['PNAME', 'PPRICE', 'PSTOCK', 'PORIGIN', 'PDATE'], dtype='str')

In [23]:
dataframe.index = ["F1", "F2", "F3", "F4"]
dataframe.columns = ["상품명", "가격", "재고", "원산지", "수확일"]
dataframe

    상품명    가격   재고  원산지         수확일
F1  오렌지  3000   50   미국  2019-01-01
F2  바나나  2000   30  필리핀  2019-02-01
F3   딸기  6000   10   한국  2019-03-01
F4   사과  4500  100   한국  2019-04-01

### dtypes 속성

In [24]:
dataframe.dtypes

상품명      str
가격     int64
재고     int64
원산지      str
수확일      str
dtype: object

In [25]:
dataframe["가격"] = dataframe["가격"].astype("float")
dataframe.dtypes

상품명        str
가격     float64
재고       int64
원산지        str
수확일        str
dtype: object

In [27]:
new_dataframe = dataframe.astype({
    "가격": "float",
    "재고": "int",
    "수확일": "datetime64[s]"
})

new_dataframe.dtypes

상품명              str
가격           float64
재고             int64
원산지              str
수확일    datetime64[s]
dtype: object

values 속성

In [28]:
# 둘다 반환 타입이 ndarray
values = dataframe.values
# values = dataframe.to_numpy()

print(type(values), "\n")
print(values)

<class 'numpy.ndarray'>

[['오렌지' 3000.0 50 '미국' '2019-01-01']
 ['바나나' 2000.0 30 '필리핀' '2019-02-01']
 ['딸기' 6000.0 10 '한국' '2019-03-01']
 ['사과' 4500.0 100 '한국' '2019-04-01']]

In [30]:
# 반환 타입이 StringArray
# values = dataframe["상품명"].values

# 반환 타입이 ndarray
values = dataframe["상품명"].to_numpy()

print(type(values), "\n")
print(values)

<class 'numpy.ndarray'>

['오렌지' '바나나' '딸기' '사과']

### shape 속성

In [31]:
print(dataframe.shape)
print(dataframe.shape[0])
print(dataframe.shape[1])
rows, cols = dataframe.shape
print(rows, cols)

(4, 5)
4
5
4 5