### 데이터 수정

In [39]:
import pandas as pd

dataframe = pd.DataFrame(data={
    "eno": [1, 2, 3, 4, 5],
    "name": ["춘봄이", "하여름", "추가을", "동겨울", "춘순이"],
    "dept": ["개발팀", "분석팀", "홍보팀", "인사팀", "설계팀"],
    "date": [
        pd.to_datetime("2015-09-22"),
        pd.to_datetime("2016-09-22"),
        pd.to_datetime("2017-09-22"),
        pd.to_datetime("2018-09-22"),
        pd.to_datetime("2019-09-22")
    ],
    "salary": [8000, 7500, 7300, 7200, 7700],
    "bonus": [500, 500, 500, 500, 500]
})

dataframe

   eno name dept       date  salary  bonus
0    1  춘봄이  개발팀 2015-09-22    8000    500
1    2  하여름  분석팀 2016-09-22    7500    500
2    3  추가을  홍보팀 2017-09-22    7300    500
3    4  동겨울  인사팀 2018-09-22    7200    500
4    5  춘순이  설계팀 2019-09-22    7700    500

단일 요소 수정

In [40]:
dataframe.loc[2, "dept"] = "개발팀"
dataframe

   eno name dept       date  salary  bonus
0    1  춘봄이  개발팀 2015-09-22    8000    500
1    2  하여름  분석팀 2016-09-22    7500    500
2    3  추가을  개발팀 2017-09-22    7300    500
3    4  동겨울  인사팀 2018-09-22    7200    500
4    5  춘순이  설계팀 2019-09-22    7700    500

범위 수정

In [41]:
dataframe.loc[0:1, "salary":"bonus"] = 0
dataframe

   eno name dept       date  salary  bonus
0    1  춘봄이  개발팀 2015-09-22       0      0
1    2  하여름  분석팀 2016-09-22       0      0
2    3  추가을  개발팀 2017-09-22    7300    500
3    4  동겨울  인사팀 2018-09-22    7200    500
4    5  춘순이  설계팀 2019-09-22    7700    500

In [42]:
dataframe.loc[0:1, "salary":"bonus"] = [8000, 500]
dataframe

   eno name dept       date  salary  bonus
0    1  춘봄이  개발팀 2015-09-22    8000    500
1    2  하여름  분석팀 2016-09-22    8000    500
2    3  추가을  개발팀 2017-09-22    7300    500
3    4  동겨울  인사팀 2018-09-22    7200    500
4    5  춘순이  설계팀 2019-09-22    7700    500

행 전체 수정

In [43]:
# 컬럼 순서와 상관없이 딕셔너리로 값을 전달하는 방법
dataframe.loc[0] = {"eno": 1, "name": "춘봄이", "dept": "개발팀", 
                    "date": pd.to_datetime("2015-09-22"), 
                    "salary": 9000, "bonus": 600}

# 컬럼 순서에 맞게 리스트로 값을 전달하는 방법
dataframe.loc[1] = [ 2, "하여름", "분석팀",
                    pd.to_datetime("2016-09-22"), 9000, 600]

dataframe

   eno name dept       date  salary  bonus
0    1  춘봄이  개발팀 2015-09-22    9000    600
1    2  하여름  분석팀 2016-09-22    9000    600
2    3  추가을  개발팀 2017-09-22    7300    500
3    4  동겨울  인사팀 2018-09-22    7200    500
4    5  춘순이  설계팀 2019-09-22    7700    500

조건에 의한 요소 수정

In [44]:
dataframe.loc[dataframe["salary"]<=7500, "bonus"] = 300
dataframe

   eno name dept       date  salary  bonus
0    1  춘봄이  개발팀 2015-09-22    9000    600
1    2  하여름  분석팀 2016-09-22    9000    600
2    3  추가을  개발팀 2017-09-22    7300    300
3    4  동겨울  인사팀 2018-09-22    7200    300
4    5  춘순이  설계팀 2019-09-22    7700    500

결측치 처리

In [45]:
dataframe.loc[0, "dept"] = None
dataframe.loc[2, "date"] = None
dataframe.loc[4, "bonus"] = None

dataframe

   eno name dept       date  salary  bonus
0    1  춘봄이  NaN 2015-09-22    9000  600.0
1    2  하여름  분석팀 2016-09-22    9000  600.0
2    3  추가을  개발팀        NaT    7300  300.0
3    4  동겨울  인사팀 2018-09-22    7200  300.0
4    5  춘순이  설계팀 2019-09-22    7700    NaN

In [46]:
dataframe.isna().sum()

eno       0
name      0
dept      1
date      1
salary    0
bonus     1
dtype: int64

In [47]:
dataframe.fillna({
    "dept": "개발팀",
    "date": pd.Timestamp.now().normalize(),
    "bonus": 300
}, inplace=True)

dataframe

   eno name dept       date  salary  bonus
0    1  춘봄이  개발팀 2015-09-22    9000  600.0
1    2  하여름  분석팀 2016-09-22    9000  600.0
2    3  추가을  개발팀 2026-05-25    7300  300.0
3    4  동겨울  인사팀 2018-09-22    7200  300.0
4    5  춘순이  설계팀 2019-09-22    7700  300.0

In [38]:
dataframe.loc[0, "dept"] = None
dataframe.loc[2, "date"] = None
dataframe.loc[4, "bonus"] = None

dataframe.dropna(inplace=True)
dataframe

   eno name dept       date  salary  bonus
1    2  하여름  분석팀 2016-09-22    9000  600.0
3    4  동겨울  인사팀 2018-09-22    7200  300.0

In [48]:
dataframe.loc[0, "dept"] = None
dataframe.loc[2, "date"] = None
dataframe.loc[4, "bonus"] = None

dataframe.dropna(subset=["dept", "date"], inplace=True)
dataframe

   eno name dept       date  salary  bonus
1    2  하여름  분석팀 2016-09-22    9000  600.0
3    4  동겨울  인사팀 2018-09-22    7200  300.0
4    5  춘순이  설계팀 2019-09-22    7700    NaN