### 데이터 검색

In [4]:
import pandas as pd

dataframe = pd.DataFrame(data={
    "eno": [100, 200, 300, 400, 500],
    "name": ["춘봄이", "하여름", "추가을", "동겨울", "춘순이"],
    "dept": ["개발팀", "분석팀", "홍보팀", "인사팀", "설계팀"],
    "date": [
        pd.to_datetime("2015-09-22"),
        pd.to_datetime("2016-09-22"),
        pd.to_datetime("2017-09-22"),
        pd.to_datetime("2018-09-22"),
        pd.to_datetime("2019-09-22")
    ],
    "salary": [8000, 7500, 7300, 7200, 7700]
})

dataframe

   eno name dept       date  salary
0  100  춘봄이  개발팀 2015-09-22    8000
1  200  하여름  분석팀 2016-09-22    7500
2  300  추가을  홍보팀 2017-09-22    7300
3  400  동겨울  인사팀 2018-09-22    7200
4  500  춘순이  설계팀 2019-09-22    7700

In [5]:

dataframe.set_index("eno", inplace=True)
dataframe

    name dept       date  salary
eno
100  춘봄이  개발팀 2015-09-22    8000
200  하여름  분석팀 2016-09-22    7500
300  추가을  홍보팀 2017-09-22    7300
400  동겨울  인사팀 2018-09-22    7200
500  춘순이  설계팀 2019-09-22    7700

단일 컬럼 가져오기

In [6]:
series = dataframe["name"]
series

eno
100    춘봄이
200    하여름
300    추가을
400    동겨울
500    춘순이
Name: name, dtype: str

In [7]:
series = dataframe.name
series

eno
100    춘봄이
200    하여름
300    추가을
400    동겨울
500    춘순이
Name: name, dtype: str

여러개의 컬럼 가져오기

In [8]:
resultDF = dataframe[["name", "dept"]]
resultDF

    name dept
eno
100  춘봄이  개발팀
200  하여름  분석팀
300  추가을  홍보팀
400  동겨울  인사팀
500  춘순이  설계팀

상하위 n개 행 가져오기

In [9]:
topDF = dataframe.head(2)
topDF

    name dept       date  salary
eno
100  춘봄이  개발팀 2015-09-22    8000
200  하여름  분석팀 2016-09-22    7500

In [10]:
bottomDF = dataframe.tail(2)
bottomDF

    name dept       date  salary
eno
400  동겨울  인사팀 2018-09-22    7200
500  춘순이  설계팀 2019-09-22    7700

단일 행 가져오기

In [13]:
dataframe

    name dept       date  salary
eno
100  춘봄이  개발팀 2015-09-22    8000
200  하여름  분석팀 2016-09-22    7500
300  추가을  홍보팀 2017-09-22    7300
400  동겨울  인사팀 2018-09-22    7200
500  춘순이  설계팀 2019-09-22    7700

In [11]:
series = dataframe.loc[300]     
series

name                      추가을
dept                      홍보팀
date      2017-09-22 00:00:00
salary                   7300
Name: 300, dtype: object

여러 개의 행 가져오기

In [14]:
resultDF = dataframe.loc[[100, 400]]  # 대괄호가 두개인점 유의
resultDF

    name dept       date  salary
eno
100  춘봄이  개발팀 2015-09-22    8000
400  동겨울  인사팀 2018-09-22    7200

행 슬라이스

In [15]:
resultDF = dataframe.loc[100:300]
resultDF

    name dept       date  salary
eno
100  춘봄이  개발팀 2015-09-22    8000
200  하여름  분석팀 2016-09-22    7500
300  추가을  홍보팀 2017-09-22    7300

조건으로 가져오기

In [18]:
dataframe["dept"]=="개발팀"

eno
100     True
200    False
300    False
400    False
500    False
Name: dept, dtype: bool

In [ ]:
resultDF = dataframe.loc[dataframe["dept"]=="개발팀"]
resultDF

<class 'pandas.Series'>

    name dept       date  salary
eno
100  춘봄이  개발팀 2015-09-22    8000

In [19]:
resultDF = dataframe.loc[dataframe["date"]>pd.to_datetime("2017-01-01")]
resultDF

    name dept       date  salary
eno
300  추가을  홍보팀 2017-09-22    7300
400  동겨울  인사팀 2018-09-22    7200
500  춘순이  설계팀 2019-09-22    7700

In [20]:
resultDF = dataframe.loc[dataframe["dept"].isin(["개발팀", "설계팀"])]
resultDF

    name dept       date  salary
eno
100  춘봄이  개발팀 2015-09-22    8000
500  춘순이  설계팀 2019-09-22    7700

행과 컬럼을 이용해서 가져오기

In [21]:
result = dataframe.loc[200, "name"]
result

'하여름'

In [22]:
resultDF = dataframe.loc[100:300, "name":"dept"]
resultDF

    name dept
eno
100  춘봄이  개발팀
200  하여름  분석팀
300  추가을  홍보팀

### 무작위 행 가져오기

In [23]:
resultDF = dataframe.sample(3)
resultDF

    name dept       date  salary
eno
300  추가을  홍보팀 2017-09-22    7300
100  춘봄이  개발팀 2015-09-22    8000
500  춘순이  설계팀 2019-09-22    7700

In [29]:
# dataframe에서 30%의 데이터를 랜덤하게 추출하여 resultDF에 저장한다.
resultDF = dataframe.sample(frac=0.3)
resultDF

    name dept       date  salary
eno
300  추가을  홍보팀 2017-09-22    7300
500  춘순이  설계팀 2019-09-22    7700

In [31]:
# random_state 매개변수에 1을 입력하여 난수 시드를 고정한다.
resultDF = dataframe.sample(frac=0.3, random_state=1)
resultDF

    name dept       date  salary
eno
300  추가을  홍보팀 2017-09-22    7300
200  하여름  분석팀 2016-09-22    7500

정렬해서 가져오기

In [32]:
resultDF = dataframe.sort_values("salary", ascending=False)
resultDF

    name dept       date  salary
eno
100  춘봄이  개발팀 2015-09-22    8000
500  춘순이  설계팀 2019-09-22    7700
200  하여름  분석팀 2016-09-22    7500
300  추가을  홍보팀 2017-09-22    7300
400  동겨울  인사팀 2018-09-22    7200