### DataFrame 생성

관련 모듈 가져오기

In [2]:
import pandas as pd
import numpy as np

딕셔너리로 DataFrame 생성

In [17]:
col1_series = pd.Series(["오렌지", "바나나", "딸기", "사과"])
col2_list = [3000, 2000, 6000, 4500]
col3_array = np.array([50, 30, 10, 100])
col4_array = np.array(["미국", "필리핀", "한국", "한국"])

dataframe = pd.DataFrame({
    "PNAME":col1_series,
    "PPRICE":col2_list,
    "PSTOCK":col3_array,
    "PORIGIN":col4_array
})

dataframe

  PNAME  PPRICE  PSTOCK PORIGIN
0   오렌지    3000      50      미국
1   바나나    2000      30     필리핀
2    딸기    6000      10      한국
3    사과    4500     100      한국

2중 리스트 또는 2차원 배열로 DataFrame 생성

In [14]:
data =[["오렌지", 3000, 50, "미국"],
       ["바나나", 2000, 30, "필리핀"],  
       ["딸기", 6000, 10, "한국"], 
       ["사과", 4500, 100, "한국"]]

# data =np.array([["오렌지", 3000, 50, "미국"],
#                     ["바나나", 2000, 30, "필리핀"],  
#                     ["딸기", 6000, 10, "한국"], 
#                     ["사과", 4500, 100, "한국"]])

dataframe = pd.DataFrame(
    data, 
    columns=["PNAME", "PPRICE", "PSTOCK", "PORIGIN"])

dataframe

  PNAME  PPRICE  PSTOCK PORIGIN
0   오렌지    3000      50      미국
1   바나나    2000      30     필리핀
2    딸기    6000      10      한국
3    사과    4500     100      한국

In [24]:
col1_series = pd.Series(["오렌지", "바나나", "딸기", "사과"])
col2_list = [3000, 2000, 6000, 4500]
col3_array = np.array([50, 30, 10, 100])
col4_array = np.array(["미국", "필리핀", "한국", "한국"])

column_stack_data = np.column_stack(
    np.array([col1_series, col2_list, col3_array, col4_array]))
column_stack_data

dataframe = pd.DataFrame(
    data = column_stack_data,
    columns=["PNAME", "PPRICE", "PSTOCK", "PORIGIN"]
)

dataframe

  PNAME PPRICE PSTOCK PORIGIN
0   오렌지   3000     50      미국
1   바나나   2000     30     필리핀
2    딸기   6000     10      한국
3    사과   4500    100      한국

DataFrame을 복제

In [21]:
# dataframe의 복제본 생성
dataframe_cloned = dataframe.copy()

# 행 레이블과 컬럼 레이블을 이용해서 값을 변경
dataframe_cloned.loc[0, "PSTOCK"] = 1000
dataframe_cloned.loc[1, "PSTOCK"] = 2000

# 원본이 변경되지 않았는지 확인
print(dataframe)
print()
print(dataframe_cloned)

  PNAME PPRICE PSTOCK PORIGIN
0   오렌지   3000     50      미국
1   바나나   2000     30     필리핀
2    딸기   6000     10      한국
3    사과   4500    100      한국

  PNAME PPRICE PSTOCK PORIGIN
0   오렌지   3000   1000      미국
1   바나나   2000   2000     필리핀
2    딸기   6000     10      한국
3    사과   4500    100      한국

컬럼을 행 레이블로 세팅

In [25]:
pid = ["F1", "F2", "F3", "F4"]
pname = ["오렌지", "바나나", "딸기", "사과"]
pprice = [3000, 2000, 6000, 4500]
pstock = np.array([50, 30, 10, 100])
porigin = np.array(["미국", "필리핀", "한국", "한국"])

dataframe = pd.DataFrame({
    "PID": pid,
    "PNAME":pname,
    "PPRICE":pprice,
    "PSTOCK":pstock,
    "PORIGIN":porigin
})

dataframe.set_index("PID", inplace=True)
dataframe

    PNAME  PPRICE  PSTOCK PORIGIN
PID
F1    오렌지    3000      50      미국
F2    바나나    2000      30     필리핀
F3     딸기    6000      10      한국
F4     사과    4500     100      한국