In [26]:
import pandas as pd

dataframe = pd.DataFrame(columns=["eno", "name", "dept", "date", "salary"])

하나의 행을 추가

In [27]:
# pd.concat() 함수를 사용하여 새로운 행을 데이터프레임에 추가하는 방법
# - ignore_index=True 를 사용하면 기존 인덱스를 무시하고 새 인덱스를 생성함
new_df = pd.DataFrame([
    { "eno": 1, "name": "김하나", "dept": "개발팀",
      "date": pd.to_datetime("2020-09-22"), "salary": 7800 }
])
dataframe = pd.concat([dataframe, new_df], ignore_index=True)

# loc[] 인덱서를 사용하여 새로운 행을 데이터프레임에 추가하는 방법
new_row = { "eno": 2, "name": "홍길동",   "dept": "분석팀", 
            "date": pd.to_datetime("2021-09-22"), "salary": 7600}
dataframe.loc[len(dataframe)] = new_row

dataframe

  eno name dept                 date salary
0   1  김하나  개발팀  2020-09-22 00:00:00   7800
1   2  홍길동  분석팀  2021-09-22 00:00:00   7600

여러 개의 행을 추가

In [28]:
new_df = pd.DataFrame(
    [
        {"eno": 3, "name": "홍길서",   "dept": "홍보팀", 
         "date": pd.to_datetime("2022-09-22"), "salary": 7400},
        
        {"eno": 4, "name": "홍길남",   "dept": "인사팀", 
         "date": pd.to_datetime("2023-09-22"), "salary": 7300},
        
        {"eno": 5, "name": "홍길북","dept": "설계팀", 
         "date": pd.to_datetime("2024-09-22"), "salary": 7900},
    ]
)
dataframe = pd.concat([dataframe, new_df], ignore_index=True)

dataframe

  eno name dept                 date salary
0   1  김하나  개발팀  2020-09-22 00:00:00   7800
1   2  홍길동  분석팀  2021-09-22 00:00:00   7600
2   3  홍길서  홍보팀  2022-09-22 00:00:00   7400
3   4  홍길남  인사팀  2023-09-22 00:00:00   7300
4   5  홍길북  설계팀  2024-09-22 00:00:00   7900