### 반복 및 변환

In [1]:
import pandas as pd

In [2]:
# 샘플 데이터 준비
dataframe = pd.DataFrame({
    "eno": [1, 2, 3, 4, 5],
    "name": ["춘봄이", "하여름", "추가을", "춘순이", "김철수"],
    "dept": ["개발팀", "분석팀", "홍보팀", "설계팀", "개발팀"],
    "date": pd.to_datetime([
        "2015-09-22", "2016-09-22", "2017-09-22",
        "2019-09-22", "2020-03-15"
    ]),
    "salary": [8000, 7500, 7300, 7700, 7100],
    "bonus": [100, 200, 300, 500, 250]
})

dataframe

   eno name dept       date  salary  bonus
0    1  춘봄이  개발팀 2015-09-22    8000    100
1    2  하여름  분석팀 2016-09-22    7500    200
2    3  추가을  홍보팀 2017-09-22    7300    300
3    4  춘순이  설계팀 2019-09-22    7700    500
4    5  김철수  개발팀 2020-03-15    7100    250

##### itertuples() - 행 단위 반복

In [3]:
df_copy = dataframe.copy()
grade_list = []
for row in df_copy.itertuples():
    if row.salary >= 8000 and row.bonus >= 500:
        grade = "S"
    elif row.salary >= 7500 or row.bonus >= 400:
        grade = "A"
    elif row.salary >= 7000:
        grade = "B"
    else:
        grade = "C"    
    grade_list.append(grade)
df_copy["grade"] = grade_list
df_copy

   eno name dept       date  salary  bonus grade
0    1  춘봄이  개발팀 2015-09-22    8000    100     A
1    2  하여름  분석팀 2016-09-22    7500    200     A
2    3  추가을  홍보팀 2017-09-22    7300    300     B
3    4  춘순이  설계팀 2019-09-22    7700    500     A
4    5  김철수  개발팀 2020-03-15    7100    250     B

##### 컬럼 변환

In [4]:
# Min-Max 정규화 적용하기
df_copy = dataframe.copy()
df_copy["salary"] = df_copy["salary"].transform(
    lambda x: (x - x.min()) / (x.max() - x.min())
)
df_copy

   eno name dept       date    salary  bonus
0    1  춘봄이  개발팀 2015-09-22  1.000000    100
1    2  하여름  분석팀 2016-09-22  0.444444    200
2    3  추가을  홍보팀 2017-09-22  0.222222    300
3    4  춘순이  설계팀 2019-09-22  0.666667    500
4    5  김철수  개발팀 2020-03-15  0.000000    250

In [5]:
# 여러 컬럼에 동시에 적용하기
df_copy = dataframe.copy()
df_copy[["salary", "bonus"]] = df_copy[["salary", "bonus"]].transform(
    lambda x: (x - x.min()) / (x.max() - x.min())
)
df_copy

   eno name dept       date    salary  bonus
0    1  춘봄이  개발팀 2015-09-22  1.000000  0.000
1    2  하여름  분석팀 2016-09-22  0.444444  0.250
2    3  추가을  홍보팀 2017-09-22  0.222222  0.500
3    4  춘순이  설계팀 2019-09-22  0.666667  1.000
4    5  김철수  개발팀 2020-03-15  0.000000  0.375

In [6]:
# 표준화(평균=0, 표준편차=1) 적용하기
df_copy = dataframe.copy()
df_copy[["salary", "bonus"]] = df_copy[["salary", "bonus"]].transform(
    lambda col: (col - col.mean()) / col.std()
)
df_copy

   eno name dept       date    salary    bonus
0    1  춘봄이  개발팀 2015-09-22  1.374236 -1.14614
1    2  하여름  분석팀 2016-09-22 -0.057260 -0.47194
2    3  추가을  홍보팀 2017-09-22 -0.629858  0.20226
3    4  춘순이  설계팀 2019-09-22  0.515339  1.55066
4    5  김철수  개발팀 2020-03-15 -1.202457 -0.13484

##### 행 변환

In [7]:
df_copy = dataframe.copy()
df_copy["total_pay"] = df_copy.apply(
    lambda row: row['salary'] + row['bonus'],
    axis=1
)
df_copy

   eno name dept       date  salary  bonus  total_pay
0    1  춘봄이  개발팀 2015-09-22    8000    100       8100
1    2  하여름  분석팀 2016-09-22    7500    200       7700
2    3  추가을  홍보팀 2017-09-22    7300    300       7600
3    4  춘순이  설계팀 2019-09-22    7700    500       8200
4    5  김철수  개발팀 2020-03-15    7100    250       7350

In [8]:
def determine_grade(row):
    total = row['salary'] + row['bonus']    
    if total >= 8500:
        return "S"
    elif total >= 7800:
        return "A"
    elif total >= 7300:
        return "B"
    else:
        return "C"

df_copy = dataframe.copy()
df_copy["grade"] = df_copy.apply(
    determine_grade, 
    axis=1
)
df_copy

   eno name dept       date  salary  bonus grade
0    1  춘봄이  개발팀 2015-09-22    8000    100     A
1    2  하여름  분석팀 2016-09-22    7500    200     B
2    3  추가을  홍보팀 2017-09-22    7300    300     B
3    4  춘순이  설계팀 2019-09-22    7700    500     A
4    5  김철수  개발팀 2020-03-15    7100    250     B

##### 요소 변환

In [9]:
# 딕셔너리로 값 매핑 (가장 많이 사용!)
dept_mapping = {
    "개발팀": "DEV",
    "분석팀": "DATA",
    "홍보팀": "PR",
    "인사팀": "HR",
    "설계팀": "DESIGN"
}

df_copy = dataframe.copy()
df_copy["dept"] = df_copy["dept"].map(dept_mapping)
df_copy

   eno name    dept       date  salary  bonus
0    1  춘봄이     DEV 2015-09-22    8000    100
1    2  하여름    DATA 2016-09-22    7500    200
2    3  추가을      PR 2017-09-22    7300    300
3    4  춘순이  DESIGN 2019-09-22    7700    500
4    5  김철수     DEV 2020-03-15    7100    250