In [1]:
import pandas as pd

dataframe = pd.DataFrame({
    "height": [175, 162, 180, 158, 170],
    "sex": ['male', 'female', 'male', 'female', 'male'],
    "nation": ['korea', 'usa', 'Germany', 'korea', 'usa']
})
dataframe

   height     sex   nation
0     175    male    korea
1     162  female      usa
2     180    male  Germany
3     158  female    korea
4     170    male      usa

In [ ]:
df_copy = dataframe.copy()
# 원 핫 인코딩 컬럼 생성
dummies = pd.get_dummies(df_copy[["sex", "nation"]], dtype=int)
# 컬럼 방향으로 결합하고 기존 컬럼 제거
df_result = (pd.concat([df_copy, dummies], axis=1)
              .drop(columns=["sex", "nation"]))
df_result

   height  sex_female  sex_male  nation_Germany  nation_korea  nation_usa
0     175           0         1               0             1           0
1     162           1         0               0             0           1
2     180           0         1               1             0           0
3     158           1         0               0             1           0
4     170           0         1               0             0           1