### 데이터 연산

전체 스칼라 연산

In [5]:
import numpy as np
import pandas as pd

dataframe = pd.DataFrame(np.ones((3, 3)), columns=["A", "B", "C"])
dataframe += 10
dataframe

      A     B     C
0  11.0  11.0  11.0
1  11.0  11.0  11.0
2  11.0  11.0  11.0

컬럼별 스칼라 연산

In [6]:
dataframe = pd.DataFrame(np.ones((3, 3)), columns=["A", "B", "C"])
dataframe[["B", "C"]] += [10, -10]
dataframe

     A     B    C
0  1.0  11.0 -9.0
1  1.0  11.0 -9.0
2  1.0  11.0 -9.0

슬라이싱 범위 연산

In [8]:
dataframe = pd.DataFrame(np.ones((3, 3)), columns=["A", "B", "C"])
dataframe.loc[0:1,"B":"C"] += 10
dataframe

     A     B     C
0  1.0  11.0  11.0
1  1.0  11.0  11.0
2  1.0   1.0   1.0

In [10]:
dataframe = pd.DataFrame(np.ones((3, 3)), columns=["A", "B", "C"])
dataframe.loc[:, "B":"C"] += [10, 10]
dataframe

     A     B     C
0  1.0  11.0  11.0
1  1.0  11.0  11.0
2  1.0  11.0  11.0