### DataFrame 결합 및 병합

In [48]:
import pandas as pd

##### 행 방향으로 결합

In [49]:
df1 = pd.DataFrame({
    "name": ["홍길동", "김영수"],
    "age": [25, 30],
    "city": ["서울", "부산"]
})

df2 = pd.DataFrame({
    "name": ["이철수", "박민지"],
    "age": [28, 35],
    "city": ["대구", "인천"]
})

result = pd.concat([df1, df2], ignore_index=True)
result

  name  age city
0  홍길동   25   서울
1  김영수   30   부산
2  이철수   28   대구
3  박민지   35   인천

##### 컬럼 방향으로 결합

In [50]:
df1 = pd.DataFrame({
    "name": ["김철수", "박영희", "이민수"],
    "dept": ["개발팀", "분석팀", "인사팀"]
})

df2 = pd.DataFrame({
    "salary": [8000, 7500, 7300],
    "bonus": [500, 300, 400]
})

result = pd.concat([df1, df2], axis=1)
result

  name dept  salary  bonus
0  김철수  개발팀    8000    500
1  박영희  분석팀    7500    300
2  이민수  인사팀    7300    400

##### 병합: Inner Join

In [51]:
employees = pd.DataFrame({
    "emp_id": [1, 2, 3, 4],
    "name": ["김철수", "박영희", "이민수", "최지영"],
    "dept_id": [101, 102, 101, None]
})

departments = pd.DataFrame({
    "dept_id": [101, 102, 103, 104],
    "dept_name": ["개발팀", "분석팀", "인사팀", "영업팀"]
})

print("직원 정보:")
print(employees)

print("\n부서 정보:")
print(departments)

result = pd.merge(employees, departments, on="dept_id", how="inner")
print("\nInner Join 결과:")
print(result)

직원 정보:
   emp_id name  dept_id
0       1  김철수    101.0
1       2  박영희    102.0
2       3  이민수    101.0
3       4  최지영      NaN

부서 정보:
   dept_id dept_name
0      101       개발팀
1      102       분석팀
2      103       인사팀
3      104       영업팀

Inner Join 결과:
   emp_id name  dept_id dept_name
0       1  김철수    101.0       개발팀
1       2  박영희    102.0       분석팀
2       3  이민수    101.0       개발팀

##### 병합: Left Join

In [52]:
# Left Join: 왼쪽(employees) DataFrame의 모든 행 유지
result = pd.merge(employees, departments, on="dept_id", how="left")
result

   emp_id name  dept_id dept_name
0       1  김철수    101.0       개발팀
1       2  박영희    102.0       분석팀
2       3  이민수    101.0       개발팀
3       4  최지영      NaN       NaN

##### 병합: Right Join

In [53]:
# Right Join: 오른쪽(departments) DataFrame의 모든 행 유지
result = pd.merge(employees, departments, on="dept_id", how="right")
result

   emp_id name  dept_id dept_name
0     1.0  김철수    101.0       개발팀
1     3.0  이민수    101.0       개발팀
2     2.0  박영희    102.0       분석팀
3     NaN  NaN    103.0       인사팀
4     NaN  NaN    104.0       영업팀

##### 병합: Outer Join

In [54]:
# Outer Join: 양쪽 모든 행 유지 (결측값은 NaN)
result = pd.merge(employees, departments, on="dept_id", how="outer")
result

   emp_id name  dept_id dept_name
0     1.0  김철수    101.0       개발팀
1     3.0  이민수    101.0       개발팀
2     2.0  박영희    102.0       분석팀
3     NaN  NaN    103.0       인사팀
4     NaN  NaN    104.0       영업팀
5     4.0  최지영      NaN       NaN

##### 주문 데이터와 고객 데이터 병합

In [55]:
# 주문 데이터
orders = pd.DataFrame({
    "order_id": [1001, 1002, 1003, 1004],
    "customer_id": ["C001", "C002", "C001", "C003"],
    "product": ["노트북", "마우스", "키보드", "모니터"],
    "price": [1200000, 30000, 80000, 350000]
})
orders

   order_id customer_id product    price
0      1001        C001     노트북  1200000
1      1002        C002     마우스    30000
2      1003        C001     키보드    80000
3      1004        C003     모니터   350000

In [56]:
# 고객 데이터
customers = pd.DataFrame({
    "customer_id": ["C001", "C002", "C003"],
    "customer_name": ["김철수", "박영희", "이민수"],
    "city": ["서울", "부산", "대구"]
})
customers

  customer_id customer_name city
0        C001           김철수   서울
1        C002           박영희   부산
2        C003           이민수   대구

In [57]:

# DataFrame 병합 (고객 정보와 주문 정보 결합)
merged_df = pd.merge(orders, customers, on="customer_id", how="inner")
merged_df

   order_id customer_id product    price customer_name city
0      1001        C001     노트북  1200000           김철수   서울
1      1002        C002     마우스    30000           박영희   부산
2      1003        C001     키보드    80000           김철수   서울
3      1004        C003     모니터   350000           이민수   대구

In [62]:
# 고객별 총 구매 금액과 구매 횟수 집계
result = (merged_df.groupby(["customer_id", "customer_name"])["price"]
                   .agg(["sum", "count"])
                   .reset_index()
                   .rename(columns={"sum": "total_price", 
                                    "count": "purchase_count"}))
result

  customer_id customer_name  total_price  purchase_count
0        C001           김철수      1280000               2
1        C002           박영희        30000               1
2        C003           이민수       350000               1