In [71]:
import pandas as pd

dataframe = pd.DataFrame(data={
    "eno": [1, 2, 3, 4, 5, 6, 7, 8],
    "name": ["춘봄", "하름", "추을", "동울", "춘이", "홍동", "홍서", "홍남"],
    "dept": ["개발", "분석", "홍보", "인사", "설계", "개발", "개발", "분석"],
    "date": [
        pd.to_datetime("2015-09-22"),
        pd.to_datetime("2016-09-22"),
        pd.to_datetime("2017-09-22"),
        pd.to_datetime("2018-09-22"),
        pd.to_datetime("2019-09-22"),
        pd.to_datetime("2020-09-22"),
        pd.to_datetime("2021-09-22"),
        pd.to_datetime("2021-09-22")
    ],
    "salary": [8000, 7500, 7300, 7200, 7700, 7800, 7900, 7600]
})

dataframe

   eno name dept       date  salary
0    1   춘봄   개발 2015-09-22    8000
1    2   하름   분석 2016-09-22    7500
2    3   추을   홍보 2017-09-22    7300
3    4   동울   인사 2018-09-22    7200
4    5   춘이   설계 2019-09-22    7700
5    6   홍동   개발 2020-09-22    7800
6    7   홍서   개발 2021-09-22    7900
7    8   홍남   분석 2021-09-22    7600

In [72]:
# 레이블로 단일 행 삭제
dataframe.drop(1, inplace=True)
dataframe

   eno name dept       date  salary
0    1   춘봄   개발 2015-09-22    8000
2    3   추을   홍보 2017-09-22    7300
3    4   동울   인사 2018-09-22    7200
4    5   춘이   설계 2019-09-22    7700
5    6   홍동   개발 2020-09-22    7800
6    7   홍서   개발 2021-09-22    7900
7    8   홍남   분석 2021-09-22    7600

In [73]:
# 여러 행 삭제
dataframe.drop([3, 4], inplace=True)
dataframe

   eno name dept       date  salary
0    1   춘봄   개발 2015-09-22    8000
2    3   추을   홍보 2017-09-22    7300
5    6   홍동   개발 2020-09-22    7800
6    7   홍서   개발 2021-09-22    7900
7    8   홍남   분석 2021-09-22    7600

In [74]:
# 레이블 범위로 여러 행 삭제
# dataframe.loc[2:5]는 양끝을 포함하는 범위로 행을 선택 
# dataframe.loc[2:5].index는 행 Index를 반환
dataframe.drop(dataframe.loc[2:5].index, inplace=True)
dataframe

   eno name dept       date  salary
0    1   춘봄   개발 2015-09-22    8000
6    7   홍서   개발 2021-09-22    7900
7    8   홍남   분석 2021-09-22    7600

행 레이블 재생성

In [61]:
dataframe.reset_index(inplace=True)
# dataframe.reset_index(inplace=True, drop=True)
dataframe

   index  eno name dept       date  salary
0      0    1   춘봄   개발 2015-09-22    8000
1      6    7   홍서   개발 2021-09-22    7900
2      7    8   홍남   분석 2021-09-22    7600

In [76]:
dataframe.set_index("eno", inplace=True)
dataframe

    name dept       date  salary
eno
1     춘봄   개발 2015-09-22    8000
7     홍서   개발 2021-09-22    7900
8     홍남   분석 2021-09-22    7600

In [77]:
dataframe.reset_index(inplace=True)
dataframe

   eno name dept       date  salary
0    1   춘봄   개발 2015-09-22    8000
1    7   홍서   개발 2021-09-22    7900
2    8   홍남   분석 2021-09-22    7600