### 데이터 요약 및 집계

In [2]:
import pandas as pd

dataframe = pd.DataFrame({
    "employee_id": [101, 102, 103, 104, 105, 106, 107, 108, 109],
    "name": ["김민수", "박영희", "이철수", "최지영", "정선미", "홍길동",
             "강민준", "윤서연", "임재현"],
    "dept": ["개발팀", "개발팀", "분석팀", "분석팀", "인사팀", "개발팀",
             "분석팀", "인사팀", "개발팀"],
    "position": ["사원", "대리", "대리", "과장", "차장", "사원",
                 "사원", "대리", "과장"],
    "salary": [3000, 4500, 4500, 6000, 7000, 3200, 3100, 4800, 6500],
    "experience": [1, 3, 3, 5, 8, 1, 2, 4, 6]
})
dataframe

   employee_id name dept position  salary  experience
0          101  김민수  개발팀       사원    3000           1
1          102  박영희  개발팀       대리    4500           3
2          103  이철수  분석팀       대리    4500           3
3          104  최지영  분석팀       과장    6000           5
4          105  정선미  인사팀       차장    7000           8
5          106  홍길동  개발팀       사원    3200           1
6          107  강민준  분석팀       사원    3100           2
7          108  윤서연  인사팀       대리    4800           4
8          109  임재현  개발팀       과장    6500           6

##### 컬럼별 집계 메소드

In [3]:
# 최대값, 중앙값, 최소값
print("최대값:")
print(dataframe[["salary", "experience"]].max(), "\n")

print("평균값:")
print(dataframe[["salary", "experience"]].mean(), "\n")

print("중앙값:")
print(dataframe[["salary", "experience"]].median(), "\n")

print("최소값:")
print(dataframe[["salary", "experience"]].min(), "\n")

print("표준편차:")
print(dataframe[["salary", "experience"]].std())

최대값:
salary        7000
experience       8
dtype: int64

평균값:
salary        4733.333333
experience       3.666667
dtype: float64

중앙값:
salary        4500.0
experience       3.0
dtype: float64

최소값:
salary        3000
experience       1
dtype: int64

표준편차:
salary        1500.000000
experience       2.345208
dtype: float64

In [4]:
total_rows = len(dataframe)  # dataframe.shape[0] 도 가능
print("전체행 개수:", total_rows)

data_count = dataframe["salary"].count()
print("데이터 개수:", data_count)

missing_count = dataframe["salary"].isna().sum()
print("결측값 개수:", missing_count)

전체행 개수: 9
데이터 개수: 9
결측값 개수: 0

##### 숫자 컬럼을 대상으로 통계 얻기

In [5]:
# 숫자형 컬럼의 기술 통계
df_result = dataframe.describe()
df_result
# print(df_result.loc["count", "salary"])

       employee_id       salary  experience
count     9.000000     9.000000    9.000000
mean    105.000000  4733.333333    3.666667
std       2.738613  1500.000000    2.345208
min     101.000000  3000.000000    1.000000
25%     103.000000  3200.000000    2.000000
50%     105.000000  4500.000000    3.000000
75%     107.000000  6000.000000    5.000000
max     109.000000  7000.000000    8.000000

##### 여러 집계 함수 동시 적용

In [6]:
# 여러 집계 함수 동시 적용
df_result = (dataframe[["salary", "experience"]]
            .agg(["mean", "sum", "min", "max"]))
df_result

            salary  experience
mean   4733.333333    3.666667
sum   42600.000000   33.000000
min    3000.000000    1.000000
max    7000.000000    8.000000

In [7]:
# 사용자 정의 집계 함수 추가
def peak_to_peak(series):
    return series.max() - series.min()

result = (dataframe["salary"].agg(["max", "min", peak_to_peak]))
result

max             7000
min             3000
peak_to_peak    4000
Name: salary, dtype: int64

##### 기본 그룹핑

In [8]:
result = dataframe.groupby("dept").size()
result

dept
개발팀    4
분석팀    3
인사팀    2
dtype: int64

In [9]:
result = (dataframe
            .groupby("dept")
            .size()
            .reset_index(name="employee_count"))
result

  dept  employee_count
0  개발팀               4
1  분석팀               3
2  인사팀               2

In [10]:
# 결측값 만들기
dataframe.loc[0, "experience"] = None

# 그룹핑 후 count()는 결측값을 제외한 개수를 반환
result = dataframe.groupby("dept").count()
result

      employee_id  name  position  salary  experience
dept
개발팀             4     4         4       4           3
분석팀             3     3         3       3           3
인사팀             2     2         2       2           2

##### 다른 컬럼을 집계하기

In [11]:
result = (dataframe.groupby("dept")["salary"]
            .mean()
            .reset_index(name="average_salary"))
result

  dept  average_salary
0  개발팀     4300.000000
1  분석팀     4533.333333
2  인사팀     5900.000000

In [12]:
result = (dataframe
            .groupby("dept")[["salary", "experience"]]
            .mean()
            .reset_index()
            .rename(columns={"salary": "average_salary", 
                             "experience": "average_experience"}))
result

  dept  average_salary  average_experience
0  개발팀     4300.000000            3.333333
1  분석팀     4533.333333            3.333333
2  인사팀     5900.000000            6.000000

In [13]:
result = (dataframe
            .groupby("dept")["salary"]
            .agg(["mean", "min", "max", "sum", "count"])
            .reset_index()
            .rename(columns={"mean": "avg_sal",
                             "min": "min_sal",
                             "max": "max_sal",
                             "sum": "total_sal",
                             "count": "emp_count"}))
result

  dept      avg_sal  min_sal  max_sal  total_sal  emp_count
0  개발팀  4300.000000     3000     6500      17200          4
1  분석팀  4533.333333     3100     6000      13600          3
2  인사팀  5900.000000     4800     7000      11800          2

##### 다중 그룹핑

In [14]:
result = (dataframe
            .groupby(["dept", "position"])
            .size()
            .reset_index(name="count"))
result

  dept position  count
0  개발팀       과장      1
1  개발팀       대리      1
2  개발팀       사원      2
3  분석팀       과장      1
4  분석팀       대리      1
5  분석팀       사원      1
6  인사팀       대리      1
7  인사팀       차장      1

In [15]:
result = (dataframe.groupby(["dept", "position"])["salary"]
            .mean()
            .reset_index()
            .rename(columns={"salary": "average_salary"}))
result

  dept position  average_salary
0  개발팀       과장          6500.0
1  개발팀       대리          4500.0
2  개발팀       사원          3100.0
3  분석팀       과장          6000.0
4  분석팀       대리          4500.0
5  분석팀       사원          3100.0
6  인사팀       대리          4800.0
7  인사팀       차장          7000.0

##### 그룹핑 후, 필터링

In [16]:
result = dataframe.groupby("dept").filter(
    lambda dept: dept["salary"].mean() >= 5000
)
result

   employee_id name dept position  salary  experience
4          105  정선미  인사팀       차장    7000         8.0
7          108  윤서연  인사팀       대리    4800         4.0

##### Pivot 테이블

In [58]:
pivot_salary = dataframe.pivot_table(
    index="dept",              # 행 레이블이 될 컬럼
    columns="position",        # 컬럼 레이블이 될 컬럼
    values="salary",           # 집계할 컬럼
    aggfunc="mean"             # 집계 함수
).reindex(columns=["차장", "과장", "대리", "사원"]) # 컬럼 순서 재정렬
pivot_salary

position      차장      과장      대리      사원
dept
개발팀          NaN  6500.0  4500.0  3100.0
분석팀          NaN  6000.0  4500.0  3100.0
인사팀       7000.0     NaN  4800.0     NaN